;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-paste
        nu/indent-more-rigidly
        nu/undo
        ))

(setq mc/cmds-to-run-once
      '(
        nu/select-all-occurrences
        nu/select-word-or-next
        ))
